=== gaiaBuildSystem/gaia/schema/distro.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "distro.json",
    "title": "The Distro Manifest Schema",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the distro",
            "type": "string"
        },
        "machine": {
            "description": "The machine type",
            "type": "string"
        },
        "version": {
            "type": "object",
            "properties": {
                "major": {
                    "type": "number"
                },
                "minor": {
                    "type": "number"
                },
                "patch": {
                    "type": "number"
                },
                "build": {
                    "type": "number"
                },
                "variant": {
                    "type": "string",
                    "enum": [
                        "ota",
                        "bootc",
                        "dev",
                        "prod"
                    ]
                },
                "codename": {
                    "type": "string"
                }
            },
            "required": [
                "major",
                "minor",
                "patch",
                "build"
            ]
        },
        "maxImgSize": {
            "type": "number"
        },
        "arch": {
            "type": "string",
            "enum": [
                "linux/amd64",
                "linux/arm64"
            ]
        },
        "searchForRecipesOn": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "excludeRecipes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "includeRecipes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "useInitramfs": {
            "type": "boolean",
            "default": true
        }
    },
    "allOf": [
        {
            "if": {
                "properties": {
                    "includeRecipes": {
                        "type": "array"
                    }
                },
                "required": [
                    "includeRecipes"
                ]
            },
            "then": {
                "not": {
                    "required": [
                        "excludeRecipes"
                    ]
                }
            },
            "else": {
                "if": {
                    "properties": {
                        "excludeRecipes": {
                            "type": "array"
                        }
                    },
                    "required": [
                        "excludeRecipes"
                    ]
                },
                "then": {
                    "not": {
                        "required": [
                            "includeRecipes"
                        ]
                    }
                }
            }
        },
        {
            "dependentSchemas": {
                "includeRecipes": {
                    "properties": {
                        "excludeRecipes": false
                    },
                    "errorMessage": "Cannot use 'includeRecipes' and 'excludeRecipes' together."
                },
                "excludeRecipes": {
                    "properties": {
                        "includeRecipes": false
                    },
                    "errorMessage": "Cannot use 'excludeRecipes' and 'includeRecipes' together."
                }
            }
        },
        {
            "oneOf": [
                {
                    "required": [
                        "includeRecipes"
                    ]
                },
                {
                    "required": [
                        "excludeRecipes"
                    ]
                }
            ]
        }
    ],
    "required": [
        "name",
        "machine",
        "version",
        "maxImgSize",
        "arch",
        "searchForRecipesOn"
    ]
}

=== gaiaBuildSystem/gaia/distro-ref-qemuarm64.json
{
    "name": "DeimOS-Reference",
    "machine": "qemuarm64",
    "arch": "linux/arm64",
    "version": {
        "major": 0,
        "minor": 1,
        "patch": 1,
        "build": 0
    },
    "maxImgSize": 3072,
    "useInitramfs": true,
    "searchForRecipesOn": [
        "cookbook"
    ],
    "excludeRecipes": [
        "grub",
        "u-boot-ram",
        "microsoft",
        "docker",
        "powershell",
        "simple-splash"
    ],
    "$schema": "./schema/distro-core.json"
}

=== gaiaBuildSystem/gaia/distro-ref-qemux86-64.json
{
    "name": "DeimOS-Reference",
    "machine": "qemux86-64",
    "arch": "linux/amd64",
    "version": {
        "major": 0,
        "minor": 1,
        "patch": 0,
        "build": 0
    },
    "maxImgSize": 1524,
    "useInitramfs": true,
    "searchForRecipesOn": [
        "cookbook"
    ],
    "excludeRecipes": [
        "u-boot-ram",
        "microsoft",
        "docker",
        "powershell",
        "neofetch",
        "simple-splash"
    ],
    "$schema": "./schema/distro-core.json"
}
