=== gaiaBuildSystem/gaia/schema/recipe.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Gaia Package",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the Recipe",
            "type": "string"
        },
        "type": {
            "description": "The type of the Recipe",
            "type": "string",
            "enum": [
                "bootloader",
                "package",
                "rootfs",
                "init",
                "config",
                "kernel",
                "kernelModule",
                "application"
            ]
        },
        "priority": {
            "description": "The priority of the Recipe. This will use if there are multiple recipes discovery with the same name. So, the property from the recipe with the highest priority will be used.",
            "type": "number"
        },
        "source": {
            "description": "The source of the Recipe. Was designed to be a git repository or an URL to a tarball or file to be fetched.",
            "type": "string",
            "pattern": "^$|^(http|https)://[^ \"]+$"
        },
        "file": {
            "description": "The file to be fetched from the source. If the source is a git repository, this property will be ignored.",
            "type": "string"
        },
        "files": {
            "description": "The files to be fetched from the source. If the source is a git repository, this property will be ignored.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "support": {
            "description": "This property is used to define the supported architectures of the recipe.",
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "linux/amd64",
                    "linux/arm64"
                ]
            },
            "minItems": 1
        },
        "ref": {
            "description": "The git reference to be fetched. If the source is a git repository, this property will be used to define the reference to be fetched.",
            "type": "object",
            "properties": {
                "linux/amd64": {
                    "type": "string"
                },
                "linux/arm64": {
                    "type": "string"
                }
            }
        },
        "checksum": {
            "description": "The checksum of the file to be fetched. If the source is a git repository, this property will be ignored.",
            "type": "object",
            "properties": {
                "linux/amd64": {
                    "type": "string"
                },
                "linux/arm64": {
                    "type": "string"
                }
            }
        },
        "hostAsContainer": {
            "description": "This property is used to define if the recipe should be built inside a container.",
            "type": "boolean",
            "default": false
        },
        "containerImage": {
            "description": "This property is used to define the container to be used to build the recipe.",
            "type": "object",
            "properties": {
                "image": {
                    "description": "The image of the Recipe. This property is used to define the image to be used to build the recipe.",
                    "type": "string"
                },
                "tag": {
                    "description": "The tag of the Recipe. This property is used to define the tag of the image to be used to build the recipe.",
                    "type": "string"
                },
                "extraConfig": {
                    "description": "The extra configuration for the container. The Gaia will bind and do some automatically configuration to run the container based in the image:tag, but some images need extra configurations like `--entrypoint=\"\"`.",
                    "type": "string"
                }
            },
            "required": [
                "image",
                "tag"
            ]
        },
        "hostDeps": {
            "description": "The host dependencies of the Recipe. This property is used by the main script check if the environment has the necessary dependencies to build the recipe.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "beforeTargetDepsRecipes": {
            "description": "This property is used to define the beforeTargetDeps scripts. They should be executable capable files and will be executed in the fetch stage.",
            "type": "array",
            "items": {}
        },
        "targetDeps": {
            "description": "The target dependencies of the Recipe. This property is used by the main script to install into the image the necessary dependencies to build the recipe.",
            "type": "array",
            "items": {}
        },
        "env": {
            "description": "The environment variables of the Recipe. This property is used by the main script to set the environment variables to build the recipe.",
            "type": "object"
        },
        "fetchRecipes": {
            "description": "This property is used to define the fetch scripts. They should be executable capable files and will be executed in the fetch stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "patchRecipes": {
            "description": "This property is used to define the patch scripts. They should be executable capable files and will be executed in the patch stage.",
            "type": "array",
            "items": {}
        },
        "buildRecipes": {
            "description": "This property is used to define the build scripts. They should be executable capable files and will be executed in the build stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "beforeDeployRecipes": {
            "description": "This property is used to define the before deploy scripts. They should be executable capable files and will be executed in the before deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "deployPureRecipes": {
            "description": "This property is used to define the pure deploy scripts. Pure deploy means that these does not depends on having rootfs. They should be executable capable files and will be executed in the pure deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "deployRecipes": {
            "description": "This property is used to define the deploy scripts. They should be executable capable files and will be executed in the deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "afterDeployRecipes": {
            "description": "This property is used to define the after deploy scripts. They should be executable capable files and will be executed in the after deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "bundleRecipes": {
            "description": "This property is used to define the bundle scripts. They should be executable capable files and will be executed in the bundle stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "cleanRecipes": {
            "description": "This property is used to define the clean scripts. They should be executable capable files and will be executed in the clean stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "initramfsRecipes": {
            "description": "This property is used to define the initramfs scripts. They should be executable capable files and will be executed in the initramfs stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "afterDeployInitramfsRecipes": {
            "description": "This property is used to define the after deploy initramfs scripts. They should be executable capable files and will be executed in the after deploy initramfs stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "merge": {
            "description": "This property is used to define if the recipes should be merged with the existing ones.",
            "type": "boolean"
        },
        "version": {
            "description": "The version of the Recipe. This property is used to define the version of the recipe.",
            "type": "string"
        }
    },
    "allOf": [
        {
            "if": {
                "properties": {
                    "hostAsContainer": {
                        "const": true
                    }
                },
                "required": [
                    "hostAsContainer"
                ]
            },
            "then": {
                "required": [
                    "containerImage"
                ]
            },
            "else": {}
        }
    ],
    "required": [
        "name",
        "type",
        "priority",
        "support"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-common/simple-splash/simple-splash.json
{
    "name": "simple-splash",
    "type": "init",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "targetDeps": [
        "procps",
        "systemd",
        "patchelf",
        "python3",
        "python3-pip",
        "scons",
        "fbset",
        "fbi"
    ],
    "afterDeployRecipes": [
        "config.ts"
    ],
    "initramfsRecipes": [
        "deployInit.sh"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-dev-tools/microsoft/microsoft.json
{
    "name": "microsoft-deb-packages",
    "type": "package",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "source": "https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb",
    "file": "packages-microsoft-prod.deb",
    "fetchRecipes": [
        "fetch.ts"
    ],
    "deployRecipes": [
        "deploy.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-common/edit/edit.json
{
    "name": "edit",
    "type": "application",
    "priority": 0,
    "version": "1.2.0",
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "hostDeps": [
        "wget",
        "tar",
        "zstd"
    ],
    "fetchRecipes": [
        "fetch.ts"
    ],
    "deployRecipes": [
        "deploy.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-common/neofetch/neofetch.json
{
    "name": "neofetch",
    "type": "config",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "source": "https://github.com/dylanaraps/neofetch",
    "ref": {
        "linux/amd64": "60d07dee6b76769d8c487a40639fb7b5a1a7bc85",
        "linux/arm64": "60d07dee6b76769d8c487a40639fb7b5a1a7bc85"
    },
    "fetchRecipes": [
        "fetch.ts"
    ],
    "deployRecipes": [
        "deploy.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-common/drm-splash/drm-splash.json
{
    "name": "drm-splash",
    "type": "init",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "source": "https://github.com/gaiaBuildSystem/drm_display.git",
    "ref": {
        "linux/amd64": "0001e60a2cd580893ab5e7b50b421b8117de7880",
        "linux/arm64": "0001e60a2cd580893ab5e7b50b421b8117de7880"
    },
    "hostAsContainer": true,
    "containerImage": {
        "image": "docker.io/pergamos/staticx",
        "tag": "bookworm",
        "extraConfig": "--privileged --pid=host --ipc=host --uts=host"
    },
    "hostDeps": [
        "build-essential",
        "wget",
        "libdrm-dev"
    ],
    "fetchRecipes": [
        "fetch.ts"
    ],
    "buildRecipes": [
        "build.sh"
    ],
    "deployRecipes": [
        "deploy.ts"
    ],
    "afterDeployRecipes": [
        "config.ts"
    ],
    "initramfsRecipes": [
        "deployInit.sh"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-debian/sid/sid.json
{
    "name": "debian-sid",
    "type": "rootfs",
    "priority": 0,
    "source": "https://github.com/debuerreotype/docker-debian-artifacts",
    "file": "sid/rootfs.tar.xz",
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "ref": {
        "linux/amd64": "06e65b40faea2bdba5d884cc89a990274c543bfb",
        "linux/arm64": "8420e1aac9977b20a62dbef5e45c44472cacba82"
    },
    "checksum": {
        "linux/amd64": "3d292fea0e8d8970b17d41f10984fd3c1ea02185ec10bf39f6791e3124f9672f",
        "linux/arm64": "cb612d270e0821738a3169b2892272a61fb6325be64d0bbf2be262610da2cfd8"
    },
    "hostDeps": [
        "mount",
        "xz-utils",
        "kpartx"
    ],
    "targetDeps": [
        "kmod",
        "locales",
        "sudo",
        "bash",
        "bash-completion",
        "util-linux",
        "nano",
        "htop",
        "e2fsprogs",
        "parted",
        "dbus",
        "udev"
    ],
    "fetchRecipes": [
        "fetch.ts"
    ],
    "patchRecipes": [],
    "buildRecipes": [
        "disk.ts",
        "buildRootfs.ts"
    ],
    "deployRecipes": [
        "update.ts"
    ],
    "cleanRecipes": [
        "umount.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-init/initramfs-busybox/initramfs-busybox.json
{
    "name": "initramfs-busybox",
    "type": "init",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "hostDeps": [
        "cpio",
        "gzip"
    ],
    "targetDeps": [
        "busybox-static"
    ],
    "initramfsRecipes": [
        "deploy.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-kernel/linux-firmware/linux-firmware.json
{
    "name": "linux-firmware",
    "type": "kernel",
    "priority": 0,
    "support": [
        "linux/arm64",
        "linux/amd64"
    ],
    "hostDeps": [],
    "targetDeps": [],
    "fetchRecipes": [],
    "patchRecipes": [],
    "buildRecipes": [],
    "beforeDeployRecipes": [
        "deploy.ts"
    ],
    "deployRecipes": [],
    "cleanRecipes": []
}
